# ===========================
# About Me
# ===========================
first_name: Hamim
last_name: Ally
photo: /media/images/profile/face-1.jpg
Age: 22



# ===========================
# Location
# ===========================
Residence: Bangladesh
City: Dhaka



# ===========================
# Contact
# ===========================
contact: 01789066358
email: hamimally3105@gmail.com



# ===========================
# Social Account
# ===========================
facebook: link
instragram: link
github: link
youtube: link



# ===========================
# My Skills
# ===========================

skills:
  - name: Web Developmet
    value: 100

  - name: Graphic Design
    value: 100

  - name: Game Development 
    value: 100

  - name: Microsoft Office
    value: 100


# ===========================
# My Skills
# ===========================

languages:
  - name: Bangla
    value: 100

  - name: English
    value: 60
  
  - name: Urdu / Hindi
    value: 70