# ===========================
# Settings
# ===========================
lang: en
charset: UTF-8
year: 2025
background: /media/images/bg/0.jpg



# ===========================
# Don't Delete this Section
# ===========================
templates_path: src/templates
widgets_path: src/widgets
pages_path:
  - src/pages
  - src/projects


