css: 
  - /assets/css/plugins/bootstrap.min.css
  - /assets/css/plugins/font-awesome.min.css
  - /assets/css/plugins/swiper.min.css
  - /assets/css/plugins/fancybox.min.css
  - /assets/css/style.min.css

js:
  - path: /assets/js/plugins/jquery.min.js
    defer: false

  - path: /assets/js/plugins/anime.min.js
    defer: true

  - path: /assets/js/plugins/swiper.min.js
    defer: true

  - path: /assets/js/plugins/progressbar.min.js
    defer: false

  - path: /assets/js/plugins/smooth-scrollbar.min.js
    defer: true

  - path: /assets/js/plugins/overscroll.min.js
    defer: true

  - path: /assets/js/plugins/typing.min.js
    defer: true

  - path: /assets/js/plugins/isotope.min.js
    defer: true

  - path: /assets/js/plugins/fancybox.min.js
    defer: true

  - path: /assets/js/plugins/swup.min.js
    defer: true

  - path: /assets/js/main.js
    defer: true